FROM mozilla/bugbug-base:latest

# Mercurial need Python2 :(
# git is required by the annotate pipeline.
RUN apk update && apk add python2 python2-dev git && \
    python2 -m ensurepip && \
    pip2 install --disable-pip-version-check --no-cache-dir mercurial==4.8 && \
    rm -rf /var/cache/apk/*
    
# Robustcheckout setup
RUN hg clone -r 6cd994e30bb1 https://hg.mozilla.org/hgcustom/version-control-tools /version-control-tools/

COPY infra/hgrc /root/.hgrc

CMD bugbug-data-commits /cache/
