FROM mozilla/bugbug-base:latest

# Mercurial need Python2 :(
# git is required by the annotate pipeline.

RUN apk update && apk add python2 python2-dev git
RUN python2 -m ensurepip
RUN pip2 install --disable-pip-version-check --no-cache-dir mercurial==4.8
RUN hg clone -r 6cd994e30bb1 https://hg.mozilla.org/hgcustom/version-control-tools /version-control-tools/
RUN rm -rf /var/cache/apk/*

COPY infra/hgrc /root/.hgrc

CMD bugbug-data-commits /cache/
