FROM python:3.7.3-alpine

# Setup dependencies in a cacheable step
COPY requirements.txt /requirements.txt

RUN apk update && apk upgrade && \
		apk add --no-cache gcc g++ libgomp lapack-dev git libexecinfo-dev make && \
		pip install --disable-pip-version-check --no-cache-dir -r /requirements.txt && \
		apk del gcc g++ && \
		rm -rf /var/cache/apk/*

COPY . /tmp/bugbug
RUN pip install /tmp/bugbug
